server:
  port: 8081
  servlet:
    context-path: /
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.105.22.86:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  application:
    name: seata-sample-purchase
seata:
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 10.105.22.110:8091
    enable-degrade: false
    disable-global-transaction: false